# Generated by Django 4.2.1 on 2023-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
                ('telefone', models.TextField(max_length=255)),
            ],
        ),
    ]
