# Generated by Django 4.2.1 on 2023-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaGit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.TextField(max_length=255)),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(max_length=350)),
                ('link_img', models.TextField(max_length=255)),
                ('quantidades', models.IntegerField()),
                ('classe', models.TextField(max_length=255)),
            ],
        ),
    ]
