# Generated by Django 4.2.1 on 2023-10-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaGit', '0003_produtos_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='promocao',
            field=models.TextField(default='NAO', max_length=3),
            preserve_default=False,
        ),
    ]
