# Generated by Django 4.2.1 on 2023-11-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaGit', '0004_produtos_promocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
